image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          script:
            - npm install
            - npm run build
          artifacts:
            - public/**
      - step:
          name: Deploy Master
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION 
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: "public"
            - pipe: atlassian/aws-cloudfront-invalidate:0.2.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $DISTRIBUTION_ID 